name: Webniac
favicon: null
layout_spectrum: 0.3754838607273996
typography_spectrum: 0.85247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050505'
    - '#767571'
    - '#cfd4d8'
    - '#b6aa82'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
